**SKLEARN**

Documentation pour Scikit-learn
https://scikit-learn.org/stable/

Dans scikit-learn  les données sont stockés dans une matrice (tableau à 2 dimensions).
On peut utiliser numpy arrays ou scipy.sparse.

La matrice est sous forme [n_samples, n_features]

sample (donnée) est un document, une figure, a CSV file, etc.

feature est une valeur quantitative, réel, booléen, entier


In [2]:

from sklearn.datasets import load_iris

iris_dataset = load_iris()

Explication pour Iris data_set

https://fr.wikipedia.org/wiki/Iris_de_Fisher

In [4]:
print("Keys of iris_dataset:\n", iris_dataset.keys())

Keys of iris_dataset:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [5]:
print("Type of data:", type(iris_dataset['data']))

Type of data: <class 'numpy.ndarray'>


In [6]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [7]:
print("Target names:", iris_dataset['target_names'])

Target names: ['setosa' 'versicolor' 'virginica']


In [8]:
print("Feature names:\n", iris_dataset['feature_names'])

Feature names:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [9]:
print("Type of data:", type(iris_dataset['data']))

Type of data: <class 'numpy.ndarray'>


In [10]:
#print("Shape of data:", iris_dataset['data'].shape)

print("Shape of data:", iris_dataset.data.shape)

Shape of data: (150, 4)


In [11]:
print("First five rows of data:\n", iris_dataset['data'][:5])

First five rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [12]:
iris_dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
print("Type of target:", type(iris_dataset['target']))

Type of target: <class 'numpy.ndarray'>


In [14]:
print("Shape of target:", iris_dataset['target'].shape)

Shape of target: (150,)


In [15]:
print("Target:\n", iris_dataset['target'])

print (type(iris_dataset))
#0: setosa, 1: versicolor, 2:  virginica

Target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'sklearn.utils._bunch.Bunch'>


In [16]:
import numpy as np

#On choisit le modèle le plus proches voisins

from sklearn.neighbors import KNeighborsClassifier



In [17]:
#Définir le modèle (estimateur avec les hyperparamètres)

#model (qui est un objet) = Constructeur (hyperparamètres)
#le premier modèle est le plus n_neighbors plus proches voisins

model1 = KNeighborsClassifier(n_neighbors =1)
print(model1)

KNeighborsClassifier(n_neighbors=1)


In [18]:
X = iris_dataset.data

y = iris_dataset.target

In [19]:
print("X \n",X[:5])

print("y \n",y[:5])

X 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
y 
 [0 0 0 0 0]


In [20]:
#on fait apprentissage,  fit

kn1 = model1.fit(X, y)



In [21]:
#on estime l'étiquette pour une nouvelle donnée , predict


x_new = np.array([ [2,3,4,1.5]])
 

#x_new = [[3.1, 5.3, 2.5, 1.5]]

#Attention à la dimension
print("shape:",x_new.shape)

print("etiquette :{}".format(kn1.predict(x_new)))

shape: (1, 4)
etiquette :[2]


In [22]:
#On change le modèle
model3 = KNeighborsClassifier(n_neighbors =3)
print(model3)

KNeighborsClassifier(n_neighbors=3)


In [23]:
kn3 = model3.fit(X, y)

In [24]:
x_new = [ [2,3,4,1.5]]

print(kn3.predict(x_new))

[1]


#### Entrainer et Tester les données

Il existe une fonction pour mélanger de données.

train_test_split

Une règle de base:

Par defaut,75 % pour l'ensemble d'apprentissage  et 25 % pour tester

Convention:
X pour données
y pour les étiquettes

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], test_size=0.22)

#X_train, X_test, y_train, y_test = train_test_split(X, y)

In [27]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train shape: (117, 4)
y_train shape: (117,)


In [28]:
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_test shape: (33, 4)
y_test shape: (33,)


In [29]:
#On fait apprentissage sur  les données X_train
#On évalue sur les données X_test

kn1 =model1.fit(X_train, y_train)


Evaluation

In [31]:


y_e1 = kn1.predict(X_test)

print(np.mean(y_e1 == y_test))

print(kn1.score(X_test, y_test))

from sklearn.metrics import accuracy_score
print(accuracy_score(y_e1,y_test))

print(y_e1)

print(y_test)

0.9696969696969697
0.9696969696969697
0.9696969696969697
[0 2 1 1 1 1 0 1 0 2 2 2 2 0 0 1 1 2 2 0 2 0 1 1 2 0 1 0 0 0 2 0 1]
[0 2 1 1 1 1 0 1 0 2 2 2 2 0 0 1 1 2 2 0 2 0 1 2 2 0 1 0 0 0 2 0 1]


In [32]:
kn3 =model3.fit(X_train, y_train)
y_e3 = kn3.predict(X_test)

print(kn3.score(X_test, y_test))


0.9393939393939394


In [33]:
y_e3 = model3.predict(X_test)



print(kn3.score(X_test, y_test))


print(y_e3)

print(y_test)

0.9393939393939394
[0 2 1 2 1 1 0 1 0 2 2 2 2 0 0 1 1 2 2 0 2 0 1 1 2 0 1 0 0 0 2 0 1]
[0 2 1 1 1 1 0 1 0 2 2 2 2 0 0 1 1 2 2 0 2 0 1 2 2 0 1 0 0 0 2 0 1]


Comme les modèles ne sont pas les mêmes, les scores ne sont pas obligatoirement les mêmes